### ISSUE TITLE
Falhas com OTRS 6 patch level 10 

### ISSUE THREAD

**Issue by macrazzy** [complemento/otrs.QueueAndServices#1]
O mesmo esta apresentando falhas com o OTRS 6 patch 10 ao acessar as configuraçoes de sistema, 

[Tue Aug 28 16:16:52.722572 2018] [:error] [pid 11353] Can't call method "Get" on unblessed reference at /opt/otrs//Kernel/Config/Files/ZZZZQueuesAndServices.pm line 10.\n
[Tue Aug 28 16:16:55.923019 2018] [:error] [pid 11728] Can't call method "Get" on unblessed reference at /opt/otrs//Kernel/Config/Files/ZZZZQueuesAndServices.pm line 10.\n

**Comment by ycaruso** [comment]
Olá, primeiramente obrigado por compartilhar este recurso, eu já utilizei ele em versões anteriores e sempre funcionou perfeito.
Agora na versão 6.10 também estou com problema em utilizá-lo. 
Se tiver alguma novidade me avise por gentileza, abraço.

**Comment by richieri** [comment]
Olá

Vamos analizar!

Obrigado!

Em qua, 5 de set de 2018 17:52, Yuri Caruso T. Ferreira <
notifications@github.com> escreveu:

**Comment by macrazzy** [comment]
Obrigado estamos no aguardo
